### ISSUE TITLE
Oauth support

### ISSUE THREAD

**Issue by mhughes2k** [ncstate-delta/moodle-mod_zoom#113]
More of a question than an issue. 

We've had some conversations with Zoom, and they've been a bit ...snarky...shall we say about the use of JWT for authentication. It does seem to have a couple of issues (1 JWT for the whole account it appears). They did seem to think that OAuth would be a better route for authorisation. From our perspective we'd sort of prefer Oauth as it would allow us to have different scopes of access.

So just wondering if you guys had any thoughts about this aspect?

Regards

Michael

**Comment by jrchamp** [comment]
I don't know how long the OAuth tokens last and each person would need to opt in. Definitely minimizes permissions requirements, which is a security win.

**Comment by rlorenzo** [comment]
But all the web service calls requires a JWT token... how would this work with OAuth?

**Comment by mhughes2k** [comment]
The web services API seems to support both Oauth and JWT as mechanisms for authorising the requests.

I think the “credentials” for either are passed via the Bearer header to Zoom. 

M

**Comment by jrchamp** [comment]
This was addressed by Server-to-Server OAuth support in #403
