### ISSUE TITLE
Validating field zoomurl in settings for a subdomain url

### ISSUE THREAD

**Issue by JF10R** [ncstate-delta/moodle-mod_zoom#134]
Following a comment from @rlorenzo in another issue, he made me realize I had put the wrong Zoom homepage url for the `zoomurl` setting and that is has to be a subdomain from https://zoom.us. Since the field only checks for a valid url, a standard domain without a subdomain is considered valid. 

I began searching for a way to extend the `PARAM_URL` parameter validation to see if it would be possible to validate for a subdomain that is not `www.`. 

This way the Zoom plugin could validate that the url is valid but also that it is a subdomain of zoom.us.

Points of interest (on Moodle 3.8.4+, ymmv): 
* /lib/moodlelib.php:242
* /lib/moodlelib.php:797
  * function `clean_param( $param, $type )` declaration.
* /lib/moodlelib.php:1039
   * validation process for param `PARAM_URL` calls `validateUrlSyntax( $param, 's?H?S?F?E-u-P-a?I?p?f?q?r?' )`
* /lib/validateurlsyntax.php:173
  * function `validateUrlSyntax( $urladdr )` declaration.

If I find anything interesting for the matter I'll probably end up making a pull request. For the mean time, if anyone else finds anything related to this, I believe this validation could fix issues for a few users that (like me) didn't double check their settings correctly.

**Comment by jrchamp** [comment]
So you're saying that it requires a Vanity URL? The only place that I see it being used is for an error message: https://github.com/ucla/moodle-mod_zoom/blob/f0301cc47c6de69271d27ff6e8ebb0acf7adf592/mod_form.php#L54-L57

Based on that, it seems like you should be able to use the default zoom.us value.

**Comment by rlorenzo** [comment]
@jrchamp I thought you can only make a JWT that affects your own institution by having a campus/company domain.

Never tested this plugin on a regular zoom.com instance.

**Comment by jrchamp** [comment]
The JWT can be set up before the Vanity URL is in place. Maybe that was a restriction for v1, but I've only used v2 of the API.

**Comment by jrchamp** [comment]
As this URL is only used in user-facing contexts, by validating that the input is a URL, we've done our due diligence. The URL is not used for API calls or similar and we have to be able to rely on the Moodle administrator to provide a valid base Zoom URL.
