### ISSUE TITLE
Improvement: Fully support recurring meetings

### ISSUE THREAD

**Issue by abias** [ncstate-delta/moodle-mod_zoom#189]
Hi Rex,

mod_zoom currently lets teachers
* either create meetings with a start time and a duration
* or create recurring meetings which are infinitely available.

Only with the first option, students and teachers benefit from Moodle calendar entries and reliable meeting room entry times.
However, teachers tend to create a recurring meeting activity for the whole lecture term so that they don't have to create one activity per lecture day.

Looking at the Zoom management interface directly, you will see that you are able to define a recurrence (daily, weekly, monthly). This is not possible with mod_zoom but would directly 
a) produce benefits for teachers as they still have just to create one meeting activity, but could better control when the meeting room is open and when it is not.
b) produce benefits for students as mod_zoom could then create Moodle calendar entries for each recurrence.

Thus I would like to propose to add support for defining the recurrence to mod_zoom as well, providing the same UI as the Zoom management interface:

* Weekly meetings:
![grafik](https://user-images.githubusercontent.com/1092118/106453676-f5ad3b00-6489-11eb-81ed-382b5cf04f9c.png)
* Daily meetings:
![grafik](https://user-images.githubusercontent.com/1092118/106453757-11184600-648a-11eb-8484-19edab9041ce.png)
* Monthly meetings:
![grafik](https://user-images.githubusercontent.com/1092118/106453787-1a091780-648a-11eb-935c-8f042a3cc899.png)

To realize this goal, these implementastions will have to be done:

* Add a "Recurrence" dropdown to mod_form.php
** Add the values "Daily", "Weekly", "Monthly" and "No fixed time" to this dropdown. The default will be "No fixed time".
** Hook the "Recurrence" dropdown to the "Recurring meeting" checkbox with a hideIf rule so that it is only shown as soon as the "Recurring meeting" checkbox is checked.
* Add the necessary form widgets which will hold the recurrence details to mod_form.php. 
** Ideally, stick 100% with the way how Zoom handles this in their own web interface (see screenshots).
** Hook these widgets to the "Recurrence" dropdown with hideIf rules so that they are only shown as soon as the corresponding value is selected in the "Recurrence" dropdown
* When the form is submitted and the meeting is created or updated, directly pass the values of the new widgets to the Zoom API within the "recurrence" object of the endpoint https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate and https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingupdate
* When the form is submitted and the meeting is created / updated or deleted in Zoom, create / update or delete the Moodle calendar events accordingly. There isn't a sophisticated support for recurring events in Moodle calendar. If I go to /calendar/view.php, I just can create recurring events on a weekly basis, nothing more. The approach in this case, in my point of view, would be that mod_zoom interprets the recurrence schedule which is set by the teacher and creates individual events in the Moodle calendar which are not coupled to each other in any way.

As a side note:
In real life, there will be edge cases where the recurring meeting schedule should be skipped in one week because of vacations or something like that. But mod_zoom does not need to be smarter than Zoom itself in my point of view. Teachers have to accept that there will be a meeting scheduled within the vacation in this case. If they do not accept that, they have to schedule the meetings before and after the vacation separately.

Cheers,
Alex

**Comment by rlorenzo** [comment]
I see that @jwalits has a patch to support this at https://github.com/jwalits/moodle-mod_zoom/commit/91f464282f78aa7de255b97a1063b4587e6cd287

Is this complete enough to support this feature?

**Comment by jwalits** [comment]
Hey @rlorenzo 

Thanks the note, this is still work in progress. Still a few things need cleaning up before @abias can do a in depth peer review

Regards,
Jay
