### ISSUE TITLE
Improvement: Remove HTML tags in meeting description when sending the description to Zoom

### ISSUE THREAD

**Issue by abias** [ncstate-delta/moodle-mod_zoom#190]
Hi Rex,

currently, mod_zoom sends the meeting activity title and the meeting activity description to Zoom and fills the meeting topic and the meeting description with this data.

However, descriptions in Moodle are rich-text fields and in Zoom they are not.
Because of that, you will end up with strange Zoom meeting descriptions as soon as you start using rich text in Moodle meeting descriptions:

![grafik](https://user-images.githubusercontent.com/1092118/106455535-9c92d680-648c-11eb-8af2-9d45336d0321.png)

To avoid this, I would like to propose this improvement:
When sending the meeting description from Moodle to Zoom, always remove all HTML tags and just send a plain text description.

Cheers,
Alex

**Comment by rlorenzo** [comment]
@abias We were stripping out tags before, but that was changed in https://github.com/ucla/moodle-mod_zoom/issues/79

**Comment by martinoesterreicher** [comment]
But isn´t simply cutting out the HTML tags for the zoom description a problem too?
Once the HTML tags are stripped from the text and the syncjob does it´s job again we end up with plain text in the moodle zoom activity´s description.
