### ISSUE TITLE
Description field in a Zoom learning activity and passcode

### ISSUE THREAD

**Issue by Ottendahl** [ncstate-delta/moodle-mod_zoom#196]
We experience an error where the description field in a Zoom learning activity, changes over time.

If we use bullet points, hours or days can pass and suddenly they are gone. See pictures of before and after:
![image](https://user-images.githubusercontent.com/78724308/107200391-ef720e00-69f7-11eb-8441-1270cb833d24.png)

![image](https://user-images.githubusercontent.com/78724308/107200474-07499200-69f8-11eb-877f-7ad63be64e76.png)

If we insert an image in the description then the picture disappears.

We also experience that some students on a flow cant join Zoom without the passcode, is it possible to do so that we can choose whether a passcode should be required or not?

**Comment by abias** [comment]
I assume that there is an overlap with #190 where I proposed to just send plain text descriptions to Zoom as Zoom can't handle rich text descriptions.

If you look at https://github.com/ucla/moodle-mod_zoom/blob/master/lib.php#L186 you will see that the \mod_zoom\task\update_meetings scheduled task fetched the meeting description from Zoom back to Moodle and updates the activity.

It would have to be tested, but this scheduled task could be the culprit who magically changes your activity descriptions based on the description it fetches back from Zoom and which might have been crippled there to plain text.
