### ISSUE TITLE
Support the use of Zoom's "tracking fields"

### ISSUE THREAD

**Issue by porcospino** [ncstate-delta/moodle-mod_zoom#208]
Zoom has the concept of "tracking fields", which can be used for a variety of purposes, including reporting.

https://support.zoom.us/hc/en-us/articles/115000293426-Scheduling-Tracking-Fields

The Zoom API has a method to create tracking fields:

https://marketplace.zoom.us/docs/api-reference/zoom-api/trackingfield/trackingfieldcreate

And tracking field key/values can be passed in as an array when creating a meeting:

https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingcreate

The Zoom LTI Pro application uses tracking fields so you can pass information about the Moodle course to Zoom.

https://zoomappdocs.zoom.us/lti-pro-v2/welcome/manage-and-configure#configure-tracking-field

In our specific use case, we could use this to provide the Moodle course identifier (the LTI context_id or context_label) to Zoom as the echo360_course_context, which would allow Zoom recordings to be published automatically to the corresponding section in Echo360.

https://integration.echo360.com/hc/en-us/articles/360055663171

Would this be of interest to other institutions?

**Comment by jrchamp** [comment]
I am interested in the possibilities. Specifically, it would be nice to get the recording integration benefits of the LTI Pro without the need to install the LTI Pro Marketplace app. If Echo360 / Panopto / other systems are using these Tracking fields to automatically map recordings into folders, there may be a "common ground" configuration structure.

Mainly I want a way for the users to tell an automatic ingestion process which of their Zoom recordings they want to go into which folders on the recording tool.

**Comment by porcospino** [comment]
Many thanks, @haietza! Will get testing this immediately.
