### ISSUE TITLE
Fix DB schema check error

### ISSUE THREAD

**Issue by foxlapinou** [ncstate-delta/moodle-mod_zoom#212]
I've first installed Zoom plugin 3.3 on my Moodle sites. Since then, i've updated them to Zoom 3.4.

Now, when i use /admin/cli/check_database_schema.php i see these problems for Zoom :
 * column 'option_host_video' has default '1', expected '0' (I)
 * column 'option_participants_video' has default '1', expected '0' (I)
 * column 'option_mute_upon_entry' has default '0', expected '1' (I)

I think there is a difference between install files, and update files, and db/upgrade.php file should certainly be fixed for that.

It seems to be the opposite of #141# https://github.com/ucla/moodle-mod_zoom/pull/141

**Comment by jrchamp** [comment]
Ah, so it installed the "bad" defaults and when the defaults were "fixed" there was no db/upgrade.php to make sure that the column defaults were fixed to match.

**Comment by smbader** [comment]
So, in this location...

https://github.com/ncstate-delta/moodle-mod_zoom/blob/e8d004be70ded28ab4cfa922de7125ecbd9ad230/db/upgrade.php#L433-L435

I think you'll want to start with a block of code like this...

```php
    if ($oldversion < 2020100800) {
        // Check and/or change 3 defaults to match #141 changes
        // TODO: Actually write the code to change the fields.
    }
```

Hope this helps!
