### ISSUE TITLE
Reached maximum daily rate

### ISSUE THREAD

**Issue by DHusband81** [ncstate-delta/moodle-mod_zoom#246]
Since the last update, I am getting the following error with the date relevant to the day I attempt it.
'Reached the maximum daily rate limit for this API. Retry at Thursday, 15 April 2021, 1:00 AM'
I cannot do anything until the next day.
Looking in Zoom at my API log call log, there are lots of calls each a second apart. However, I have only attempted two actions. 
I have to wait until tomorrow to test a theory but I think it occurs when I 'Duplicate' the meeting. The meeting in this case was in the past. I duplicate the meeting to get all the information and then go in to change the time of the meeting and who it is restricted to.
Please advise, as getting locked out of being able to create or edit meetings is proving very problematic when on a deadline.

David

**Comment by rlorenzo** [comment]
@DHusband81 That is not something we can control. The API limits are determined by the Zoom API: https://marketplace.zoom.us/docs/api-reference/rate-limits

If you are managing meetings be aware of the following limit:

> A single user may only use up to 100 requests per day (UTC) to create, update, or delete meetings. This 24-hour period resets at 00:00 UTC, not the user or account’s local timezone.

**Comment by DHusband81** [comment]
Thank you for the reply.
I am aware of the limits with Zoom, but it was the first action I had taken that day on the system and then could not take any further actions. As I mentioned above, the logs showed many calls logged during the time I clicked duplicate.
The following day I created the meetings all from scratch rather than using duplicate and all worked fine. There is only me on the account, so the levels set by the API could not be reached by me alone.

**Comment by jrchamp** [comment]
If someone is available and interested in testing which API calls and how many of each occur when a single Zoom activity is duplicated in Moodle, there may be an opportunity for a performance enhancement here. If it is looping on itself and exhausting all of the API calls, that seems like a bug, but the testing would help determine what's happening here.
