### ISSUE TITLE
Active user is listed in alternative host user picker

### ISSUE THREAD

**Issue by phette23** [ncstate-delta/moodle-mod_zoom#248]
This is a minor issue but with the user picker in the `showalternativehosts` setting, the current user who is creating the Zoom activity (and thus will be host) is listed as an available option in the user picker. It seems that, if you save the activity, they're only listed under Host and not Alternative Host but I could see this being potentially confusing and causing some of our faculty to believe they need to always add themselves as alternative hosts or else they won't be able to run the meeting.

**Comment by jrchamp** [comment]
Interesting! It sounds like we caught that case after the activity has been created, so the affected code is probably relying on the zoom object existing to remove the "current" user from the alternative hosts list.

**Comment by abias** [comment]
Hey @phette23 @jrchamp ,

please look at the comments in https://github.com/ncstate-delta/moodle-mod_zoom/blob/master/locallib.php#L577-L582. 

When I implemented the alternative hosts picker, I saw a fundamental conflict between the user picker's list and the 'schedule for' feature which I couldn't resolve in the available time back then.

So, just looking at the code, the activity is working as expected. But I agreed that, looking at UX and support cases, there is room for improvement.

Cheers,
Alex
