### ISSUE TITLE
Mod stop working (V3.6) : Only available for Paid account

### ISSUE THREAD

**Issue by obook** [ncstate-delta/moodle-mod_zoom#251]
Hello,
We have an official "K-12 School Time Limit Removal" account for Education Nationale (France). Since v3.6 update, the Zoom plugin do not works any more, the error message is " Zoom received a bad request: Only available for Paid account.
Thank you for your help.
Olivier

**Comment by jrchamp** [comment]
Does an older version of the plugin still work for you? The string "Only available for Paid account" is coming from Zoom's API, not from this plugin.

**Comment by obook** [comment]
For instance, we have paid for the service as the situation was urgent.

**Comment by jrchamp** [comment]
My guess, given the number of users who are having this same issue, is that Zoom stopped offering API access for the "free school accounts" they started offering last year. I don't have any way to test it myself, so it would be good to know if any version of the plugin is working for people who are experiencing this issue.

**Comment by smbader** [comment]
The module is dependent on the API. If the issue has something to do with the module and its ability to connect, we certainly should fix it.  However, it seems like Zoom restricted (maybe unintentionally) the API to certain account types. If the API isn't available to the account being used, there's not much we can do to help.
