### ISSUE TITLE
populate_zoom_from_response() should not always return a modified timemodified value

### ISSUE THREAD

**Issue by abias** [ncstate-delta/moodle-mod_zoom#255]
In #253 , it has been detected that populate_zoom_from_response() always returns a modified timemodified value even if no field is changed.

During the review of #253, @jrchamp stated:

> I think the timemodified value is being set in the populate_zoom_from_response() function to simplify the number of places where the value needs to be set. It's not really a good thing, because it means that we have several places that are directly updating the zoom table. This is dangerous, because we might need to call rebuild_course_cache(), zoom_calendar_item_update() and/or zoom_grade_item_update() depending on what has changed. If you look at the individual cases, you'll see that this is not handled consistently. In fact, you'll see that the PHPUnit tests (which should only be skipping the remote API calls) use a custom code block instead of following the production code path.
> 
> [...] To simplify our ability to continue moving forward with "bite-size" changes, [...] a separate issue that tries to resolve the "consistent updates for the zoom table" problem should be created.

This is the issue to investigate possible improvements.

**Comment by smbader** [comment]
Suggestion: Remove `$newzoom->timemodified = time();` from lib.php:223 and properly set the `timemodified` value when the record is actually being updated.
