### ISSUE TITLE
TODO: loadmeeting.php does not treat alternative host the same as the true host

### ISSUE THREAD

**Issue by jrchamp** [ncstate-delta/moodle-mod_zoom#257]
Maybe this should be more like view.php's approach.

Anyone have a good reason to not have $userishost set to true for loadmeeting.php?

**Comment by abias** [comment]
Looking at the code, I understand that `loadmeeting.php` differentiates between the true host and everyone else.
The true host is sent to `$zoom->start_url` and everyone else to `$zoom->join_url`.

The immediate question which arises for me is: How does it work then that alternative hosts can start the meeting as well if they are just sent to `$zoom->join_url`? And I assume that Zoom, if the alternative host is logged into the client with his Zoom account, is identified and automagically allowed to start the meeting as well.

Looking at https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meeting, I read:
> The `start_url` of a Meeting is a URL using which a host or an alternative host can start the Meeting.

So my answer to your question would be: Yes, while the functionality seems to work automagically for alternative hosts as well currently, we should change this behaviour and send alternative hosts to `$zoom->start_url` as well.
