### ISSUE TITLE
Add user settings check for new meeting creation

### ISSUE THREAD

**Issue by haietza** [ncstate-delta/moodle-mod_zoom#88]
It would be great if the plugin could check a user's settings for new meetings (i.e. if they have the require a password for new meetings enabled) and incorporate those into the creation of a new meeting in Moodle (i.e. automatically enter a password in the add Zoom meeting form, or generate a warning when a user tries to create a Zoom activity in Moodle without entering a password). Along the same lines, if the user has enabled the appending of the password hash to the join URL, having this URL be used in the Moodle activity would also be helpful.

Thank you!

**Comment by jrchamp** [comment]
Rather than add a password interface, I would probably fetch the password back on create (along with the join URL - potentially with the embedded password) and display those details within the activity.

**Comment by haietza** [comment]
@jrchamp That sounds like a good option as well, since the Zoom interface has the auto password generation.

**Comment by jrchamp** [comment]
This may have been resolved by #177. For now, I'll mark this as closed and if this does not resolve the issue, please feel free to reopen.
